# after changes to this file, you need to restart the jekyll server (ctrl-c + bundle exec jekyll serve)
collections:
  reports:
  pebs:
  reports-wp:
    output: true
  pebs-wp:
    output: true

# set defaults for layouts (except the ones in _layouts)
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: "" #root
      type: "reports-wp"
    values:
      layout: "report_wp_template"

  - scope:
      path: ""
      type: "pebs"
    values:
      layout: "peb_template"

  - scope:
      path: ""
      type: "pebs-wp"
    values:
      layout: "peb_wp_template"


# configuration Variables
# baseurl: ""
# url: "/"
# url: "localhost:4000"
